version: '3'
services:
  microservice1:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - redis
  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin1
      - RABBITMQ_DEFAULT_PASS=admin1
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"